### ISSUE TITLE
Support location type?

### ISSUE THREAD

**Issue by ottob** [martinlindhe/google-geolocate#3]
In our old custom code we had support for location types.

From https://developers.google.com/maps/documentation/geocoding/intro
> "ROOFTOP" indicates that the returned result is a precise geocode for which we have location information accurate down to street address precision.

My thought was to add a `LocationType string` to the point so we could do this: 

```go
if p.LocationType != "ROOFTOP" {
    fmt.Println("this probably wasn't the result you expected")
}
```
What do you think about this?

**Comment by martinlindhe** [comment]
Sounds useful. I'd do it something like
```go
type LocationType int
const (
    Unset LocationType = iota
    Rooftop
    RangeInterpolated
    GeometricCenter
    Approximate
)
```

and a `func (g *GoogleGeo) SetLocationType(l LocationType)`

patch would be welcome!

EDIT: noticed the api supported multiple location types. You're right, lets use a string instead
